services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: postgres-sql-rat
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - spring-network
    restart: unless-stopped

  mail-dev:
    image: maildev/maildev
    container_name: maildev-rat
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-network
    restart: unless-stopped

  rat-api:
    container_name: rat-api
    image: rat/backend:1.0.0
    ports:
      - "9999:9999"
    networks:
        - spring-network
    depends_on:
      - postgres

  rat-web:
    container_name: rat-web
    image: rat/frontend:1.0.0
    ports:
      - "4200:80"
    networks:
        - spring-network
    depends_on:
      - rat-api

networks:
  spring-network:
        driver: bridge

volumes:
    postgres:
      driver: local