/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { findReviewsByTool } from '../fn/review/find-reviews-by-tool';
import { FindReviewsByTool$Params } from '../fn/review/find-reviews-by-tool';
import { PageResponseDtoReviewResponseDto } from '../models/page-response-dto-review-response-dto';
import { saveReview } from '../fn/review/save-review';
import { SaveReview$Params } from '../fn/review/save-review';


/**
 * Review API
 */
@Injectable({ providedIn: 'root' })
export class ReviewService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `saveReview()` */
  static readonly SaveReviewPath = '/reviews';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveReview()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveReview$Response(params: SaveReview$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveReview(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveReview$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveReview(params: SaveReview$Params, context?: HttpContext): Observable<number> {
    return this.saveReview$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findReviewsByTool()` */
  static readonly FindReviewsByToolPath = '/reviews/tool/{tool-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findReviewsByTool()` instead.
   *
   * This method doesn't expect any request body.
   */
  findReviewsByTool$Response(params: FindReviewsByTool$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseDtoReviewResponseDto>> {
    return findReviewsByTool(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findReviewsByTool$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findReviewsByTool(params: FindReviewsByTool$Params, context?: HttpContext): Observable<PageResponseDtoReviewResponseDto> {
    return this.findReviewsByTool$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseDtoReviewResponseDto>): PageResponseDtoReviewResponseDto => r.body)
    );
  }

}
