/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ToolResponseDto } from '../../models/tool-response-dto';

export interface GetTool$Params {
  'tool-id': number;
}

export function getTool(http: HttpClient, rootUrl: string, params: GetTool$Params, context?: HttpContext): Observable<StrictHttpResponse<ToolResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getTool.PATH, 'get');
  if (params) {
    rb.path('tool-id', params['tool-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ToolResponseDto>;
    })
  );
}

getTool.PATH = '/tools/{tool-id}';
