/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReviewResponseDto } from '../models/review-response-dto';
export interface PageResponseDtoReviewResponseDto {
  content?: Array<ReviewResponseDto>;
  first?: boolean;
  last?: boolean;
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
