/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReviewResponseDto {
  content?: string;
  id?: number;
  isOwner?: boolean;
  rating?: number;
  title?: string;
}
