/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ToolTransactionDto {
  averageRating?: number;
  description?: string;
  id?: number;
  manufacturer?: string;
  name?: string;
  returnApproved?: boolean;
  returned?: boolean;
}
