/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ToolRequestDto {
  description: string;
  id?: number;
  manufacturer: string;
  name: string;
  shareable?: boolean;
}
