spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rent_a_tool_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: user
    password: password
    properties:
      mail:
        smtp:
          auth: true
#          ssl:
#            enable: true
#            trust: "*"
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/rat-realm"
application:
  file:
    uploads:
      photos-directory: ./uploads
  security:
    cors:
      origins: http://localhost:4200,http://localhost:8080
#  security:
#    jwt:
#      secret-key: 63FDD813AA2A9922746B3EA81DCC1ABCDEFFEDCBA99999FFFDDDEEFF9999FFDDABCDEF
#      expiration: 86400000
#    mailing:
#      frontend:
#        activation-url: http://localhost:4200/activate-account
#        activation-code-length: 6 # in characters
#        activation-code-expiration: 15 # in minutes
#        activation-code-characters: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
#        activation-code-subject: Activate your account
server:
  port: 9999